namespace Entities;
public class UserProducts
{
    public int ID { get; set; } // Auto-generated by the database
    public int UserID { get; set; }
    public int ProductID { get; set; }
    public DateOnly AssignedDate { get; set; } = DateOnly.FromDateTime(DateTime.Now); // Default value
}
